### ISSUE TITLE
Read simulation and Raven issues

### ISSUE THREAD

**Issue by crj0139** [lvrcek/GNNome-assembly#11]
I have been unable to get this past Raven.  The seqrequester program gives me the following error every time that I run pipeline.py:

"ERROR: Don't know how long to make the reads. Set -distribution or -length"

If I simulate reads using another program, then put them in simulate/chr1/raw, the pipeline will run a bit further but following raven crashes with a non-specific error:

"Step 0: generating graphs for reads in 0.fasta
Path to the reads: /ocean/projects/bio220033p/crj39/Assemblies/GNNome-assembly/data/simulated/chr1/raw/0.fasta
Starting raven at: /ocean/projects/bio220033p/crj39/Assemblies/GNNome-assembly/vendor/raven/build/bin/raven
Parameters: --identity 0.99 -k29 -w9 -t32 -p0
Assembly output: assembly.fasta

[raven::] loaded 731 sequences 0.042683s
[raven::Graph::Construct] minimized 0 - 731 / 731 0.272052s
[raven::Graph::Construct] mapped sequences 0.120643s
[raven::Graph::Construct] annotated piles 0.001718s
[raven::Graph::Construct] filtered overlaps 0.232881s
[raven::Graph::Construct] removed contained sequences 0.000014s
[raven::Graph::Construct] removed chimeric sequences 0.001704s
[raven::Graph::Construct] reached checkpoint 0.004957s
[raven::Graph::Construct] minimized 0 - 463 / 463 0.326245s
[raven::Graph::Construct] mapped valid sequences 0.336586s
[raven::Graph::Construct] updated overlaps 0.000010s
[raven::Graph::Construct] removed false overlaps 0.010328s
[raven::Graph::Construct] stored 926 nodes 0.011106s
[raven::Graph::Construct] stored 0 edges 0.000000s
[raven::Graph::Construct] reached checkpoint 0.014007s
[raven::Graph::Construct] 1.334490s
[raven::Graph::Assemble] removed transitive edges 0.000028s
[raven::Graph::Assemble] reached checkpoint 0.013977s
[raven::Graph::Assemble] removed tips and bubbles 0.000023s
[raven::Graph::Assemble] reached checkpoint 0.013770s
[raven::Graph::Assemble] removed long edges 0.002454s
[raven::Graph::Assemble] reached checkpoint 0.014359s
[raven::Graph::Assemble] 0.046142s
[raven::] 1.525321s

Raven generated the graph! Processing...
Traceback (most recent call last):
  File "./pipeline.py", line 347, in <module>
    generate_graphs(data_path, all_chr)
  File "./pipeline.py", line 148, in generate_graphs
    graph_dataset.AssemblyGraphDataset(chr_sim_path, nb_pos_enc=None, specs=specs, generate=True)
  File "/ocean/projects/bio220033p/crj39/Assemblies/GNNome-assembly/graph_dataset.py", line 66, in __init__
    super().__init__(name='assembly_graphs', raw_dir=raw_dir, save_dir=save_dir)
  File "/jet/home/crj39/.local/lib/python3.8/site-packages/dgl/data/dgl_dataset.py", line 113, in __init__
    self._load()
  File "/jet/home/crj39/.local/lib/python3.8/site-packages/dgl/data/dgl_dataset.py", line 204, in _load
    self.process()
  File "/ocean/projects/bio220033p/crj39/Assemblies/GNNome-assembly/graph_dataset.py", line 126, in process
    graph, pred, succ, reads, edges, labels = graph_parser.from_csv(os.path.join(self.tmp_dir, f'{idx}_graph_1.csv'), reads_path)
  File "/ocean/projects/bio220033p/crj39/Assemblies/GNNome-assembly/graph_parser.py", line 297, in from_csv
    graph_dgl = dgl.from_networkx(graph_nx,
  File "/jet/home/crj39/.local/lib/python3.8/site-packages/dgl/convert.py", line 1260, in from_networkx
    g.ndata[attr] = F.copy_to(_batcher(attr_dict[attr]), g.device)
  File "/jet/home/crj39/.local/lib/python3.8/site-packages/dgl/convert.py", line 1249, in _batcher
    if F.is_tensor(lst[0]):
IndexError: list index out of range"

This seems to happen both when using my own data and when running the pipeline as prepared with example data.

Here is my command:
python ./pipeline.py --data ./data --out mito_test1

**Comment by crj0139** [comment]
> For seqrequester, it seems like you didn't set up the distribution for simulating the reads. You can try to run it with `-distribution pacbio-hifi` which will use a predefined distribution for HiFi reads. You can read more about it here: https://github.com/marbl/seqrequester
> 
> The issue you mention seems to not be in Raven, but in the DGL dataset. I will look into it and get back to you, at the moment I'm not sure why it happens.

Thank you, yes I was hesitant to post this because it easily could be something in my environment (I have never used a deep-learning environment before).  The seqrequester command here does not work when trying by itself either, regardless of the fact I set the -distribution flag:

seqrequester simulate -genome ./contigs.fasta -genomesize 260000000 -coverage 40 -distribution ./Software/seqrequester/build/share/seqrequester/pacbio-hifi

"ERROR: Don't know how long to make the reads. Set -distribution or -length"

I posted about this on the seqrequester github page, waiting to hear back.

My conda environment:


# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
appdirs                   1.4.4              pyhd3eb1b0_0    anaconda
blas                      1.0                         mkl    anaconda
brotlipy                  0.7.0           py38h27cfd23_1003    anaconda
bzip2                     1.0.8                h7b6447c_0
c-ares                    1.18.1               h7f8727e_0
ca-certificates           2022.12.7            ha878542_0    conda-forge
certifi                   2021.5.30                pypi_0    pypi
cffi                      1.15.1           py38h74dc2b5_0    anaconda
chardet                   4.0.0                    pypi_0    pypi
charset-normalizer        2.0.4              pyhd3eb1b0_0    anaconda
cmake                     3.22.1               h1fce559_0
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
configparser              5.2.0                    pypi_0    pypi
cryptography              38.0.4           py38h9ce1e76_0    anaconda
cycler                    0.10.0                   pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
expat                     2.4.4                h295c915_0
fftw                      3.3.9                h27cfd23_1    anaconda
gitdb                     4.0.9                    pypi_0    pypi
gitpython                 3.1.27                   pypi_0    pypi
gmp                       6.2.1                h295c915_3    anaconda
gmpy2                     2.1.2            py38heeb90bb_0    anaconda
idna                      2.10                     pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561    anaconda
joblib                    1.0.1                    pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
krb5                      1.19.2               hac12032_0
ld_impl_linux-64          2.38                 h1181459_1
libcurl                   7.82.0               h0b77cf5_0
libedit                   3.1.20210910         h7f8727e_0
libev                     4.33                 h7f8727e_1
libffi                    3.3                  he6710b0_2
libgcc-ng                 11.2.0               h1234567_0
libgfortran-ng            11.2.0               h00389a5_1    anaconda
libgfortran5              11.2.0               h1234567_1    anaconda
libgomp                   11.2.0               h1234567_0
libnghttp2                1.46.0               hce63b2e_0
libssh2                   1.10.0               h8f2d780_0
libstdcxx-ng              11.2.0               h1234567_0
libuv                     1.40.0               h7b6447c_0
lz4-c                     1.9.3                h295c915_1
matplotlib                3.4.2                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640    anaconda
mkl-service               2.4.0            py38h7f8727e_0    anaconda
mkl_fft                   1.3.1            py38hd3c417c_0    anaconda
mkl_random                1.2.2            py38h51133e4_0    anaconda
mpc                       1.1.0                h10f8cd9_1    anaconda
mpfr                      4.0.2                hb69a4c5_1    anaconda
mpmath                    1.2.1            py38h06a4308_0    anaconda
ncurses                   6.3                  h7f8727e_2
networkx                  2.5.1                    pypi_0    pypi
ninja                     1.10.2               h06a4308_5
ninja-base                1.10.2               hd09550d_5
numpy                     1.20.3                   pypi_0    pypi
numpy-base                1.23.5           py38h31eccc5_0    anaconda
openssl                   1.1.1s               h7f8727e_0    anaconda
packaging                 22.0             py38h06a4308_0    anaconda
pillow                    8.2.0                    pypi_0    pypi
pip                       21.2.4           py38h06a4308_0
pooch                     1.4.0              pyhd3eb1b0_0    anaconda
promise                   2.3                      pypi_0    pypi
protobuf                  3.20.1                   pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0    anaconda
pyopenssl                 22.0.0             pyhd3eb1b0_0    anaconda
pyparsing                 2.4.7                    pypi_0    pypi
pysocks                   1.7.1            py38h06a4308_0    anaconda
python                    3.8.13               h12debd9_0
python-dateutil           2.8.1                    pypi_0    pypi
ravenpy                   1.8.1                    pypi_0    pypi
readline                  8.1.2                h7f8727e_1
requests                  2.25.1                   pypi_0    pypi
rhash                     1.4.1                h3c74f83_1
scikit-learn              0.24.2                   pypi_0    pypi
scipy                     1.6.3                    pypi_0    pypi
sentry-sdk                1.5.12                   pypi_0    pypi
setuptools                61.2.0           py38h06a4308_0
shortuuid                 1.0.9                    pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1    anaconda
sqlite                    3.38.3               hc218d9a_0
subprocess32              3.5.4                    pypi_0    pypi
sympy                     1.11.1           py38h06a4308_0    anaconda
threadpoolctl             2.1.0                    pypi_0    pypi
tk                        8.6.11               h1ccaba5_1
tqdm                      4.62.2                   pypi_0    pypi
typing-extensions         3.10.0.0                 pypi_0    pypi
urllib3                   1.26.5                   pypi_0    pypi
wandb                     0.12.1                   pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0
xz                        5.2.5                h7f8727e_1
zlib                      1.2.12               h7f8727e_2
zstd                      1.5.2                ha4553b6_0



And the pip environment while running:


Package                       Version
----------------------------- -----------------
addict                        2.4.0
alabaster                     0.7.13
appdirs                       1.4.4
attrs                         21.4.0
autopep8                      2.0.2
Babel                         2.12.1
biopython                     1.79
blessed                       1.19.1
boto                          2.49.0
boto3                         1.24.34
boto3-stubs                   1.24.34
botocore                      1.27.34
botocore-stubs                1.27.34
brotlipy                      0.7.0
Cactus                        2.1.1
certifi                       2022.12.7
cffi                          1.15.1
chardet                       4.0.0
charset-normalizer            2.1.0
cigar                         0.1.3
click                         8.1.3
cmake                         3.26.0
colorama                      0.4.6
configparser                  5.2.0
contourpy                     1.0.7
cryptography                  38.0.4
cycler                        0.10.0
Cython                        0.29.33
decorator                     4.4.2
dgl                           1.0.1+cu117
dglgo                         0.0.2
dill                          0.3.5.1
dinopy                        2.2.1
docker                        5.0.3
docker-pycreds                0.4.0
docutils                      0.19
enlighten                     1.10.2
fonttools                     4.38.0
future                        0.18.2
futures                       3.1.1
gitdb                         4.0.9
GitPython                     3.1.27
gmpy2                         2.1.2
h5py                          3.8.0
idna                          3.4
igraph                        0.9.11
imagesize                     1.4.1
importlib-metadata            6.0.0
importlib-resources           5.12.0
iniconfig                     1.1.1
intervaltree                  3.1.0
isort                         5.12.0
Jinja2                        3.1.2
jmespath                      1.0.1
joblib                        1.0.1
kiwisolver                    1.3.1
littleutils                   0.2.2
MarkupSafe                    2.1.2
matplotlib                    3.4.2
mkl-fft                       1.3.1
mkl-random                    1.2.2
mkl-service                   2.4.0
mpmath                        1.3.0
mypy-boto3-s3                 1.24.0
nasm                          0.1.0
networkx                      2.5.1
numpy                         1.23.5
numpydoc                      1.5.0
ogb                           1.3.5
outdated                      0.2.2
packaging                     21.3
pandas                        1.5.3
pathtools                     0.1.2
Pillow                        8.2.0
pip                           23.0.1
pluggy                        1.0.0
pooch                         1.4.0
portalocker                   2.7.0
prefixed                      0.3.2
promise                       2.3
protobuf                      3.20.1
psutil                        5.9.1
py                            1.11.0
py-tes                        0.4.2
pycodestyle                   2.10.0
pycparser                     2.21
pydantic                      1.10.6
Pygments                      2.14.0
pyOpenSSL                     22.0.0
pyparsing                     2.4.7
pysam                         0.20.0
PySocks                       1.7.1
pytest                        7.1.2
python-dateutil               2.8.1
python-igraph                 0.9.11
pytz                          2022.1
PyYAML                        6.0
ravenpy                       1.8.1
rdkit-pypi                    2022.9.5
requests                      2.28.1
ruamel.yaml                   0.17.21
ruamel.yaml.clib              0.2.7
s3transfer                    0.6.0
scikit-learn                  0.24.2
scipy                         1.10.0
sentry-sdk                    1.5.12
setproctitle                  1.3.2
setuptools                    63.2.0
shortuuid                     1.0.9
six                           1.16.0
sklearn                       0.0.post1
smmap                         5.0.0
snowballstemmer               2.2.0
sonLib                        2.0
sortedcontainers              2.4.0
Sphinx                        6.1.3
sphinxcontrib-applehelp       1.0.4
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.1
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
subprocess32                  3.5.4
sympy                         1.11.1
texttable                     1.6.4
threadpoolctl                 2.1.0
toil                          5.6.0
tomli                         2.0.1
torch                         1.13.1+cu116
torch-scatter                 2.1.0+pt113cu116
torch-sparse                  0.6.16+pt113cu116
torchaudio                    0.13.1+cu116
torchvision                   0.14.1+cu116
tqdm                          4.65.0
typer                         0.7.0
types-s3transfer              0.6.0.post2
typing-extensions             3.10.0.0
urllib3                       1.26.14
wandb                         0.12.1
wcwidth                       0.2.5
websocket-client              1.3.3
wheel                         0.37.1
yasm                          0.1.0a1
zipp                          3.15.0
zlib-state                    0.1.5



On the system I use, it is cuda 11.7.1 and I have tried running this with one GPU (v100-16) on a shared partition.

**Comment by lvrcek** [comment]
It might be that there is some clash in the dependencies, as it is usually not recommended to mix packages installed with conda and pip (or at least not install conda packages after you have started installing packages with pip inside a conda environment).

Could you try to create a new environment, where you will have no packages installed, and install dependencies only with pip:
`pip install -r requriements.txt`.

Another potential cause could be versions of PyTorch and DGL. For example, I see that in your environment torch is installed for CUDA version 11.6, while DGL version is installed for CUDA 11.7. You might want to get those two to match, and both of them to match the CUDA version installed on your system.

**Comment by crj0139** [comment]
Late arrival; this was an issue with the seqrequester repo and has been fixed for some time.  Closing!
