### ISSUE TITLE
how to get NGA value? i didn't find the gff file of human chromosome

### ISSUE THREAD

**Issue by songyu2022** [lvrcek/GNNome-assembly#13]
Thanks for your work. I saw that you supply the NGA value in your paper, but i didn't find the gff file in your project. Can you tell me how to get it?

**Comment by lvrcek** [comment]
NGA50 value is based on the comparison of your assembly with the reference genome. You just need 2 FASTA files, no need for GFF. I computed these values with Quast: https://github.com/ablab/quast
