### ISSUE TITLE
Hifiasm_error correction_question

### ISSUE THREAD

**Issue by yao-chenxin** [lvrcek/GNNome-assembly#9]
Hi,author:
I would like to ask you how the reads after Hifiasm error correction are obtained from the bin file?
What software is used?
The original sentence in the article:
We first error-correct reads with hifiasm [16], thus reducing amount of mismatches, insertions, and
deletions in the reads.
 
 I am looking forward to your reply. Thanks.

**Comment by lvrcek** [comment]
Hi yao-chenxin,

We extract the error-corrected sequences from the FASTA file. Apart from the bin file, you should also see a file whose name is ending in `.ec.fa`. This is the file where the error-corrected sequences are stored.

For example, if you run Hifiasm with the following command:
```bash
./hifiasm -o output -t 32 --write-paf --write-ec  reads.fastq
```
You should see a file called `output.ec.fa` inside your working directory.

Let me know if you have any firther questions!

**Comment by yao-chenxin** [comment]
Hi,author:
Thank you very much for your reply.



With best wishes!













At 2022-08-03 11:32:36, "Lovro Vrček" ***@***.***> wrote:

Hi yao-chenxin,

We extract the error-corrected sequences from the FASTA file. Apart from the bin file, you should also see a file whose name is ending in .ec.fa. This is the file where the error-corrected sequences are stored.

For example, if you run Hifiasm with the following command:

./hifiasm -o output -t 32 --write-paf --write-ec  reads.fastq

You should see a file called output.ec.fa inside your working directory.

Let me know if you have any firther questions!
